// <auto-generated />
namespace MiniProject1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fk_pjid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk_pjid));
        
        string IMigrationMetadata.Id
        {
            get { return "202403311126010_fk_pjid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
